import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ReactNode } from 'react';

import GlobalStyles from '@/app/globalStyles';
import StyledComponentsRegistry from '@/lib/registry';
import StyledComponentsThemeRegistry from '@/lib/themeRegistry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<GlobalStyles />
				<StyledComponentsThemeRegistry>
					<StyledComponentsRegistry>{children}</StyledComponentsRegistry>
				</StyledComponentsThemeRegistry>
			</body>
		</html>
	);
}
